### ISSUE TITLE
Build succeeds on 0.72, but fails on 0.74

### ISSUE THREAD

**Issue by humanplayer2** [milgra/sov#28]
I don't know if it's my system or an issue in release 0.74, but I cannot compile it, though 0.72 compiles fine.

Edit: 0.73 compiles fine, too.

```
rasmus@x301:~/tmp/sov-0.74$ ninja -C build
ninja: Entering directory `build'
[29/64] Compiling C object sov.p/src_zen_core_zc_log.c.o
FAILED: sov.p/src_zen_core_zc_log.c.o 
cc -Isov.p -I. -I.. -I../src/sov/config -I../src/sov/tree -I../src/sov/json -I../src/sov/utils -I../src/sov -I../src/zen_core -I../src/zen_gfx -I/usr/include/freetype2 -I/usr/include/libpng16 -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -std=c99 -O3 '-DPKG_DATADIR="/usr/local/share/sov"' '-DSOV_VERSION="0.74"' -MD -MQ sov.p/src_zen_core_zc_log.c.o -MF sov.p/src_zen_core_zc_log.c.o.d -o sov.p/src_zen_core_zc_log.c.o -c ../src/zen_core/zc_log.c
../src/zen_core/zc_log.c: In function ‘zc_log’:
../src/zen_core/zc_log.c:90:21: error: storage size of ‘ts’ isn’t known
   90 |     struct timespec ts;
      |                     ^~
../src/zen_core/zc_log.c:91:9: warning: implicit declaration of function ‘clock_gettime’ [-Wimplicit-function-declaration]
   91 |     if (clock_gettime(CLOCK_REALTIME, &ts) != 0)
      |         ^~~~~~~~~~~~~
../src/zen_core/zc_log.c:91:23: error: ‘CLOCK_REALTIME’ undeclared (first use in this function)
   91 |     if (clock_gettime(CLOCK_REALTIME, &ts) != 0)
      |                       ^~~~~~~~~~~~~~
../src/zen_core/zc_log.c:91:23: note: each undeclared identifier is reported only once for each function it appears in
../src/zen_core/zc_log.c:90:21: warning: unused variable ‘ts’ [-Wunused-variable]
   90 |     struct timespec ts;
      |                     ^~
[31/64] Compiling C object sov.p/src_zen_core_zc_map.c.o
ninja: build stopped: subcommand failed.
```

**Comment by softmoth** [comment]
```
af3b3edbbbc903ccc5fb8920c86419b3862555f0 is the first bad commit
commit af3b3edbbbc903ccc5fb8920c86419b3862555f0
Author: Milan Toth <milgra@milgra.com>
Date:   Tue Oct 4 13:18:55 2022 +0000

    refactor

 meson.build                                        |  13 +-
 src/sov/json/json.c                                |   1 +
 src/sov/kvlines.c                                  |   1 +
 src/sov/main.c                                     |  59 +++--
 src/sov/tree/tree_drawer.c                         |  20 +-
 src/sov/tree/tree_reader.c                         |   8 +-
 src/sov/tree_test.c                                |  31 ++-
 .../zc_bitmap.c => sov/utils/bm_rgba_util.c}       |  84 +-----
 src/sov/utils/cstr_util.c                          | 268 +++++++++++++++++++
 src/zen_core/zc_bm_rgba.c                          |  78 ++++++
 src/zen_core/zc_cstring.c                          | 295 ++-------------------
 src/zen_core/zc_cstrpath.c                         | 108 --------
 src/zen_core/zc_log.c                              |  21 +-
 src/zen_core/zc_path.c                             | 106 ++++++++
 src/zen_core/zc_vector.c                           | 275 ++++++++++---------
 src/{zen_core/zc_graphics.c => zen_gfx/zc_draw.c}  |  88 +++---
 src/{zen_text/text.c => zen_gfx/zc_text.c}         | 123 ++++++---
 17 files changed, 853 insertions(+), 726 deletions(-)
 rename src/{zen_core/zc_bitmap.c => sov/utils/bm_rgba_util.c} (59%)
 create mode 100644 src/sov/utils/cstr_util.c
 create mode 100644 src/zen_core/zc_bm_rgba.c
 delete mode 100644 src/zen_core/zc_cstrpath.c
 create mode 100644 src/zen_core/zc_path.c
 rename src/{zen_core/zc_graphics.c => zen_gfx/zc_draw.c} (83%)
 rename src/{zen_text/text.c => zen_gfx/zc_text.c} (85%)
```

**Comment by milgra** [comment]
Hi, what distro do you use? #include <time.h> is there so maybe on your system it is in some different header.

**Comment by humanplayer2** [comment]
My apologies for forgetting to reply. I am unsure what distro I was on on that machine at the time. As I suppose this is dated by now, given the number of releases since, I'll close it to clean up.
